/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_six_payx_util_JniUtil */

#ifndef _Included_cn_six_payx_util_JniUtil
#define _Included_cn_six_payx_util_JniUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_six_payx_util_JniUtil
 * Method:    getKey
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_six_payx_util_JniUtil_getKey
  (JNIEnv *, jclass);

/*
 * Class:     cn_six_payx_util_JniUtil
 * Method:    getNo
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cn_six_payx_util_JniUtil_getNo
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
